### PR TITLE
Customizations Reset Button

### PR DESCRIPTION
**Pull request by Leo40Git**
~~Completely untested because the customization thing straight-up doesn't load for me (and it isn't my fault).~~
`resetModules()` is OK? The reset button itself is probably completely wrong, though.

### CODE REVIEW

**Comment by Leo40Git** [comment]
Current issues:
- Button looks completely wrong and is also tiny (I think I'm adding its label incorrectly)
- Navbar breaks after reset (this also happens on the live site if the dropdown button is spam-clicked)

**Comment by Leo40Git** [comment]
What it currently looks like:  
firefox_Wsn9qgVljH

**Comment by micwoj92** [comment]
why close?

**Comment by Leo40Git** [comment]
So someone with a better understanding of how to do web stuff can do it.

**Pull request closed without merging**
